### ISSUE TITLE
Castle Stars error

### ISSUE THREAD

**Issue by impeeza** [sonich2401/SM64_Save_File_Converter#1]
Hi, first at all, thanks for your great work.

When you select the sub menu Castle Stars, the last one "Mario Wings Over the Rainbow" has the wrong title: "Ma _ir_ o Wings Over the Rainbow" and when you toggle the value for that star the false/true indicator always stay on False.

**Comment by sonich2401** [comment]
Thanks for your help @impeeza. I'm glad someone is getting a use out of this program :)
I am a bad speller so thanks for pointing that speeling mistake out.
I did notice some bits would stay on forever but it seemed to fix itself so I guess that bug is still a thing. Thanks for telling me.
I am re-working the EEPROM struct so that every bit is its own variable so that should fix that issue.

I really appreciate your help but could you tell me what version you were using? There is a folder with the old Windows only GUI version that currently has more functionality and there is one in a folder called SM64FM which has a newer Linux/Windows version that is more stable but I am working on finishing the features. If you could tell me what version (probably SM64FM I am guessing) that would help me out a ton. 

Thanks, 
Ren.

**Comment by impeeza** [comment]
@sonich2401 Hi, regards from Colombia, I did recently start to use the program and is very easy and useful.

I am using the version 0.1c for Windows it have only a file called sm64SaveFileManager.exe, a default.config empty.eep and credits.crdts,  and a folder called "pic" with several files on it, I found some of them are no needed too.  let me know if I can help with more, some testing or anything.

I haven't installed Visual Studio but I have used MSYS in the past.

again thanks for your work.

**Comment by sonich2401** [comment]
> @sonich2401 Hi, regards from Colombia, I did recently start to use the program and is very easy and useful.
> 
> I am using the version 0.1c for Windows it have only a file called sm64SaveFileManager.exe, a default.config empty.eep and credits.crdts, and a folder called "pic" with several files on it, I found some of them are no needed too. let me know if I can help with more, some testing or anything.
> 
> I haven't installed Visual Studio but I have used MSYS in the past.
> 
> again thanks for your work.

Thank you my friend! Yes that is the Windows only version. It has known to be unstable and testers on Linux have reported that it corrupts or deletes your save file. Because of that I'm re-writing the EEPROM back end that handles save files all together. It's finals week for college but after school I'll release a new, much more stable version of the old version with the GUI.

(also yea I forgot that I left a bunch of pictures in that 'pic' folder lol)

Glad the program was simple to use :)

**Comment by impeeza** [comment]
Perfect, Count on my, Have a nice day.

**Comment by sonich2401** [comment]
> Perfect, Count on my, Have a nice day.

The newest release of the program should Fix this issue. I completely rewrote the entire program so it should run even better than before.

Thanks for the feedback my friend :)

**Comment by impeeza** [comment]
Thanks a lot for your work
