### ISSUE TITLE
SM64 SAVE FILE CONVERTER CRASH

### ISSUE THREAD

**Issue by JuanSosaa8** [sonich2401/SM64_Save_File_Converter#3]
When I load an already used save and edit it, when I hit save the program crashes, and when I reopen the file I edited, the same thing happens.

When I create a blank save, no changes appear inside the game.

**Comment by sonich2401** [comment]
Hello and thank you for using my program. This is a duplicate question to #2 and I know exactly what causes the crash. I am talking with a developer of a dependancy that I use to get the issue resolved. You can see the full conversation chain here.

Due to this issue being a duplicate I will close this issue https://github.com/sonich2401/SM64_Save_File_Converter/issues/2
